name: SonarCloud

on:
  push:
    branches:
      - '**'

jobs:
  sonarcloud-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pytest
        pip install sonar-scanner
    - name: Run tests with coverage
      run: pytest --cov=./
    - name: Upload coverage report to SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: sonar-scanner -Dsonar.coverage.reportPaths=coverage.xml
