name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request_target:
    types: [ opened, synchronize, reopened, edited ]
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov    

    - name: Test with pytest
      run: |
        pytest --cov=src tests/ --cov-report=xml:coverage.xml

    - name: Override Coverage Source Path for Sonar
      run: |
        cat coverage.xml
        sed -i 's/\/home\/runner\/work\/sonarcloud_testing\/sonarcloud_testing\//\/github\/workspace\//g' coverage.xml
        cat coverage.xml

    - name: Analyze code with SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

