name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov    

    - name: Test with pytest
      run: |
        pytest tests/ --cov=src --cov-report=xml:./src/coverage.xml    
        cat coverage.xml

    - name: Override Coverage Source Path for Sonar
      run: sed -i "s/<source>\/home\/runner\/work\/sonarcloud_testing\/sonarcloud_testing\/src<\/source>/<source>\/github\/workspace<\/source>/g" /home/runner/work/sonarcloud_testing/sonarcloud_testing/coverage.xml

    - name: Analyze code with SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

